export default {
  FONT_FAMILY: 'fontFamily',
  FONT_COLOR: 'fontColor',
  FONT_SIZE: 'fontSize',
  FONT_ALIGN: 'fontAlign',
  IS_FONT_BOLD: 'isFontBold',
  IS_FONT_ITALIC: 'isFontItalic',
  IS_FONT_UNDERLINE: 'isFontUnderline',
  BORDER_COLOR: 'borderColor',
  BORDER_SIZE: 'borderSize',
  BORDER_RADIUS: 'borderRadius',
  SHADOW_COLOR: 'shadowColor',
  SHADOW_DIRECTION: 'shadowDirection',
  SHADOW_SIZE: 'shadowSize',
  BACKGROUND_COLOR: 'backgroundColor',
  BACKGROUND_COLOR_TO: 'backgroundColorTo',
}
